scribe:
  auth:
    login-url: https://scribe-hub-production.us.auth0.com
    grant-type: client_credentials
    enable: true
    audience: api.production.scribesecurity.com
  url: https://airflow.scribesecurity.com
  enable: true
